data:
  dataset : didmdn_rain
  path : ./datasets/DID-MDN/
  train_split : train
  val_split : val
  test_split : test
  patch_size : 512
  aug_data : false  # Set as False for fair comparison

model : 'did_mdn'
resume : true

batch_size : 2
optimizer :
  name : 'adam'
  lr : 5.0e-3

checkpoint_dir : './checkpoints/did_mdn/'
show_dir : './checkpoints/did_mdn/'
pretrained_model_dir : './pretrained_models/did_mdn/'
save_steps : 1000
max_iters : 20000
n_workers : 8

log_level : 'info'

vis :
  use : true
  env : 'did_mdn'